name: Deploy Django to EC2

on:
  push:
    branches: "master"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the latest code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Run the deployment script
    - name: Run Deployment
      run: |
        ssh -i ${{ secrets.EC2_SSH_KEY }} ubuntu@gnanadhandayuthapani.com 'bash -s' < deploy_script.sh
      env:
        ACTIONS_RUNNER_DEBUG: false
